// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pucpkrhkkezeoxwqjryd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1Y3Brcmhra2V6ZW94d3FqcnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTE5NjcsImV4cCI6MjA1ODgyNzk2N30.BqZfVnPwopitM3F6mJ2Lu3aE11zE_csn8EADEyf8EZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);